import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/styles/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import AppLayout from "@/shared/ui/AppLayout/AppLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <ConfigProvider 
          theme={{
            components: {
              Layout: {
                headerBg: '#FEF2FF',
                footerBg: '#FEF2FF',
                
              }
            },
          }}><AppLayout>{children}</AppLayout></ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
